[package]
name = "postman2openapi"
description = "Convert a Postman collection to an OpenAPI definition. "
homepage = "https://github.com/kevinswiber/postman2openapi"
repository = "https://github.com/kevinswiber/postman2openapi"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Kevin Swiber <kswiber@gmail.com>"]
build = "build.rs"
edition = "2018"

[lib]
name = "postman2openapi"
path = "src/lib.rs"

[[bin]]
name = "postman2openapi"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
atty = "0.2"
clap = "3.0.0-beta.1"
convert_case = "0.4.0"
lazy_static = "1.4.0"
regex = "1"
semver = "0.10.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["raw_value"]}
serde_yaml = "0.8"
thiserror = "1.0"
url = { version = "2.1.1", features = ["serde"] }