[package]
name = "postman2openapi"
version = "0.1.0"
authors = ["Kevin Swiber <kswiber@gmail.com>"]
edition = "2018"

[lib]
name = "postman2openapi"
path = "src/lib.rs"

[[bin]]
name = "postman2openapi"
path = "src/main.rs"

[dependencies]
# openapi = { git = "https://github.com/softprops/openapi" }
convert_case = "0.4.0"
anyhow = "1.0"
thiserror = "1.0"
semver = "0.9.0"
serde_yaml = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["raw_value"]}
regex = "1"
url = "1.7"
url_serde = "0.2"
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "0.5"